title: Line Rider Web Guide
description: The comprehensive guide to the web version of Line Rider.
baseurl: "/home"
repository: Malizma333/line-rider-web-guide

# Build settings
open_url: true
theme: just-the-docs
plugins:
  - jekyll-feed
