title: Line Rider Web Guide
description: The comprehensive guide to the web version of Line Rider.
baseurl: "/home"
repository: Malizma333/line-rider-web-guide

# Build settings
open_url: true
theme: just-the-docs
plugins:
  - jekyll-feed

# Customization
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true
  focus_shortcut_key: 'f'

nav_external_links:
  - title: Line Rider API
    url: https://malizma333.github.io/line-rider-web-docs/
  - title: Official Discord
    url: https://discord.gg/KqsTrwqjxV

aux_links:
  "linerider.com":
    - "https://www.linerider.com"

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true
gh_edit_link_text: "Contribute to this guide on GitHub"
gh_edit_repository: "https://github.com/Malizma333/line-rider-web-guide/"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

color_scheme: light

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red